// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GzBDFsMQi9frAuznAzwj1h3YweVwN08',
    appId: '1:923483901149:web:7246ba8c509f81430edf34',
    messagingSenderId: '923483901149',
    projectId: 'clinic-web-ffff0',
    authDomain: 'clinic-web-ffff0.firebaseapp.com',
    databaseURL: 'https://clinic-web-ffff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-web-ffff0.firebasestorage.app',
    measurementId: 'G-QWB41EQRTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIRccuDEHTV-UBoUI4DCDdYgMeACU9jYI',
    appId: '1:923483901149:android:dfd67c0c2580a4df0edf34',
    messagingSenderId: '923483901149',
    projectId: 'clinic-web-ffff0',
    databaseURL: 'https://clinic-web-ffff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-web-ffff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo2thMMqc_lNLf8e_E4jC5o1KggjHzVbA',
    appId: '1:923483901149:ios:e4dfcc1eb377c8cf0edf34',
    messagingSenderId: '923483901149',
    projectId: 'clinic-web-ffff0',
    databaseURL: 'https://clinic-web-ffff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-web-ffff0.firebasestorage.app',
    iosBundleId: 'com.example.clinicWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo2thMMqc_lNLf8e_E4jC5o1KggjHzVbA',
    appId: '1:923483901149:ios:e4dfcc1eb377c8cf0edf34',
    messagingSenderId: '923483901149',
    projectId: 'clinic-web-ffff0',
    databaseURL: 'https://clinic-web-ffff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-web-ffff0.firebasestorage.app',
    iosBundleId: 'com.example.clinicWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3GzBDFsMQi9frAuznAzwj1h3YweVwN08',
    appId: '1:923483901149:web:7246ba8c509f81430edf34',
    messagingSenderId: '923483901149',
    projectId: 'clinic-web-ffff0',
    authDomain: 'clinic-web-ffff0.firebaseapp.com',
    databaseURL: 'https://clinic-web-ffff0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-web-ffff0.firebasestorage.app',
    measurementId: 'G-QWB41EQRTW',
  );

}